#!/bin/sh

# Version 1.2 - Fma965
# Based on https://wu.renjie.im/blog/network/ax88u-vlan

HAServer=192.168.1.4
UnraidServer=192.168.1.3

# Make sure the script is indeed invoked
touch /tmp/000-firewall-start

logger -t "tag_lanport4" "firewall-start: applying INPUT rules"

# Allow connection to router for DHCP.
iptables -I INPUT -i vlan20 -m state --state NEW -j ACCEPT
iptables -I INPUT -i vlan30 -m state --state NEW -j ACCEPT
iptables -I INPUT -i vlan80 -m state --state NEW -j ACCEPT

logger -t "tag_lanport4" "firewall-start: applying FORWARD rules"

### --- Seems to be default, so not needed ---
# Forbid packets from VLAN20/30 from being forwarded to other interfaces
#iptables -I FORWARD -i vlan20 -j DROP
#iptables -I FORWARD -i vlan30 -j DROP

# But allow packet forwarding inside own interfaces
#iptables -I FORWARD -i vlan20 -o vlan20 -j ACCEPT
#iptables -I FORWARD -i vlan30 -o vlan30 -j ACCEPT
### --- Seems to be default, so not needed ---

# Allow one-way traffic from lan to VLAN20/30/80
iptables -I FORWARD -i br0 -o vlan20 -j ACCEPT
iptables -I FORWARD -i vlan20 -o br0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -i br0 -o vlan30 -j ACCEPT
iptables -I FORWARD -i vlan30 -o br0 -m state --state RELATED,ESTABLISHED -j ACCEPT
iptables -I FORWARD -i bro -o vlan80 -j ACCEPT
iptables -I FORWARD -i vlan80 -o br0 -m state --state RELATED,ESTABLISHED -j ACCEPT

# Allow internet access on VLAN20 and VLAN 80 but not VLAN30
iptables -I FORWARD -i vlan20 -o vlan3880 -j ACCEPT
iptables -I FORWARD -i vlan80 -o vlan3880 -j ACCEPT

# Allow Access to Home Assistant on VLAN30 potentially lock this to specific ports in the future
iptables -I FORWARD -i vlan30 -d $HAServer -j ACCEPT 

# Allow Access to Home Assistant on VLAN20 potentially lock this to specific ports in the future
iptables -I FORWARD -i vlan20 -d $HAServer -j ACCEPT 

# Allow NTP to internet on VLAN30
iptables -I FORWARD -i vlan30 -p udp --dport 123 -o vlan3880 -j ACCEPT

logger -t "tag_lanport4" "firewall-start: all done"
date >> /tmp/000-firewall-start
