#!/bin/sh

# Version 1.0 - Fma965
# Based on https://wu.renjie.im/blog/network/ax88u-vlan

# Make sure the script is indeed invoked
touch /tmp/000-nat-start
logger -t "isolate_port" "nat-start: applying POSTROUTING rules for br4"

# NAT inside 10.1.1.0/24 on br1
iptables -t nat -A POSTROUTING -s 10.1.1.0/24 -d 10.1.1.0/24 -o br4 -j MASQUERADE

logger -t "isolate_port" "nat-start: all done"
date >> /tmp/000-nat-start
